version: '1.0'

services:
  app:
    container_name: backend_container
    image: 'backend_app:latest'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    #sobrescreve as configurações do application.properties
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres14_container:5432/financial_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=PBattistella2024
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
#    restart: unless-stopped